name: CI workflow

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  my-fancy-build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Very Fancy Checkout
        uses: actions/checkout@v3

      - name: Fancy Dependency Installation
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Super-fancy Lint Checking with flakey 8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Ultra-fancy unit testing on your nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app

